# Generated by Django 5.1.3 on 2024-11-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('Loan_id', models.IntegerField()),
                ('Loan_type', models.CharField(max_length=30)),
                ('Loan_amt', models.IntegerField()),
                ('Customer_acno', models.IntegerField(primary_key=True, serialize=False)),
                ('Cust_name', models.CharField(max_length=50)),
            ],
        ),
    ]
